%{
    #include <stdio.h>
    #include <stdlib.h>
    #include <string.h>

    #include "calc.tab.h"
    #include "lex.yy.h"   /* generated by flex --header-file */

    typedef struct {
        char *name;
        double value;
    } Var;

    #define MAX_VARS 256

    static Var vars[MAX_VARS];
    static int var_count = 0;

    static Var *find_var(const char *name) {
        for (int i = 0; i < var_count; i++) {
            if (strcmp(vars[i].name, name) == 0) {
                return &vars[i];
            }
        }
        return NULL;
    }

    static Var *get_or_create_var(const char *name) {
        Var *v = find_var(name);
        if (v) {
            return v;
        }
        if (var_count >= MAX_VARS) {
            fprintf(stderr, "Symbol table full\n");
            exit(1);
        }

        vars[var_count].name = strdup(name);
        vars[var_count].value = 0;
        return &vars[var_count++];
    }

    int yyerror(char *s);
%}

%union {
    double num;
    char *id;
}

%token <id> COMMAND
%token <id> IDENT
%token <num> NUMBER
%token PLUS TIMES MINUS DIVIDE
%token LPAREN RPAREN
%token EOL
%token ASSIGN

%type <num> expr
%type <num> term
%type <num> factor

%left PLUS MINUS
%left TIMES DIVIDE
%right UMINUS

%start line

%%

line:
      expr EOL                 
        { printf("=%g\n", $1); }
    | IDENT ASSIGN expr EOL    
        {
            Var *v = get_or_create_var($1);
            v->value = $3;
            printf("=%g\n", $3);
        }
    | COMMAND EOL
        {
            if (strcmp($1, ":symbols") == 0 ||
                strcmp($1, ":vars") == 0 ||
                strcmp($1, ":dump") == 0) {
                printf("Symbols:\n");
                for (int i = 0; i < var_count; i++) {
                    printf("  %s = %g\n", vars[i].name, vars[i].value);
                }
            }
            else if (strcmp($1, ":reset") == 0) {
                var_count = 0;
                printf("All variables cleared.\n");
            }
            else if (strcmp($1, ":help") == 0) {
                printf("Available commands:\n");
                printf("  :symbols   Show all variables\n");
                printf("  :reset     Clear all variables\n");
                printf("  :store <file>   Save variables to a file\n");
                printf("  :load <file>    Load variables from a file\n");
                printf("  :help      Show this help message\n");
                printf("  :quit      Exit the interpreter\n");
                printf("\n");
                printf("Expressions:\n");
                printf("  Supports +, -, *, /, parentheses, unary minus\n");
                printf("  Variables can be assigned with:  name = expr\n");
            }
            else if (strcmp($1, ":quit") == 0) {
                exit(0);
            }
            else {
                printf("Unknown command: %s\n", $1);
            }
        }
    | COMMAND IDENT EOL 
        {
            if (strcmp($1, ":store") == 0) {
                FILE *f = fopen($2, "w");
                if (!f) {
                    printf("Error: cannot open %s for writing\n", $2);
                } else {
                    for (int i = 0; i < var_count; i++) {
                        fprintf(f, "%s %g\n", vars[i].name, vars[i].value);
                    }
                    fclose(f);
                    printf("Stored %d variables to %s\n", var_count, $2);
                }
            }
            else if (strcmp($1, ":load") == 0) {
                FILE *f = fopen($2, "r");
                if (!f) {
                    printf("Error: cannot open %s for reading\n", $2);
                } else {
                    var_count = 0;  // clear existing vars
                    char name[256];
                    double value;
                    while (fscanf(f, "%255s %lf", name, &value) == 2) {
                        Var *v = get_or_create_var(name);
                        v->value = value;
                    }
                    fclose(f);
                    printf("Loaded %d variables from %s\n", var_count, $2);
                }
            }
        }
    | EOL
        { /* blank line */ }
    ;

expr:
      expr PLUS term           { $$ = $1 + $3; }
    | expr MINUS term          { $$ = $1 - $3; }
    | term
    ;

term:
      term TIMES factor        { $$ = $1 * $3; }
    | term DIVIDE factor       { $$ = $1 / $3; }
    | factor
    ;

factor:
      MINUS factor %prec UMINUS { $$ = -$2; }
    | LPAREN expr RPAREN        { $$ = $2; }
    | NUMBER                    { $$ = $<num>1; }
    | IDENT                     
        {
            Var *v = find_var($1);
            if (!v) {
                printf("Error: undefined variable '%s'\n", $1);
                $$ = 0;
            } else {
                $$ = v->value;
            }
        }
    ;

%%

int main() {
    char line[1024];

    while (1) {
        printf(">>> ");
        if (!fgets(line, sizeof(line), stdin))
            break;

        YY_BUFFER_STATE buf = yy_scan_string(line);
        yyparse();
        yy_delete_buffer(buf);
    }
}

int yyerror(char *s) {
    printf("Error: %s\n", s);
    return 0;
}
